name: 'electronics_retail_dw'
version: '1.0.0'
config-version: 2

profile: 'electronics_retail_dw'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  electronics_retail_dw:
    staging:
      +materialized: view
    mart:
      +materialized: table
